# project.yml — XcodeGen configuration for Trusty Bookshelf
#
# XcodeGen generates the .xcodeproj from this single YAML file.
# This keeps the git repository clean (no binary .pbxproj diffs).
#
# Setup:
#   brew install xcodegen
#   xcodegen generate
#   open "Trusty Bookshelf.xcodeproj"

name: Trusty Bookshelf
options:
  bundleIdPrefix: com.elfak.tutorial
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    TARGETED_DEVICE_FAMILY: "1"

targets:
  Bookshelf:
    type: application
    platform: iOS
    sources:
      - path: Bookshelf
    resources:
      - path: Bookshelf/Resources
      - path: Bookshelf/CoreData/Bookshelf.xcdatamodeld
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.elfak.tutorial.Bookshelf
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Trusty Bookshelf
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait

  BookshelfTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BookshelfTests
    dependencies:
      - target: Bookshelf
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.elfak.tutorial.BookshelfTests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Bookshelf.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Bookshelf"
        BUNDLE_LOADER: "$(TEST_HOST)"
